# Generated by Django 4.0.4 on 2022-04-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(auto_now_add=True)),
                ('checkout', models.DateField(blank=True, default=None, null=True)),
                ('rental', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.rental')),
            ],
        ),
    ]
